# Generated by Django 3.1.2 on 2023-03-21 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='channel',
            name='childs',
            field=models.ManyToManyField(related_name='_channel_childs_+', to='channels.Channel'),
        ),
        migrations.AddField(
            model_name='channel',
            name='content_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.content'),
        ),
        migrations.AddField(
            model_name='channel',
            name='is_root',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='channels.content'),
        ),
        migrations.DeleteModel(
            name='ChannelLeaf',
        ),
    ]
