# Generated by Django 3.1.2 on 2023-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_auto_20230322_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='childs',
            field=models.ManyToManyField(blank=True, related_name='_channel_childs_+', to='channels.Channel'),
        ),
    ]
