# Generated by Django 3.1.2 on 2023-03-22 20:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20230322_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='content_child',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='is_root',
        ),
        migrations.RemoveField(
            model_name='content',
            name='parent',
        ),
        migrations.AddField(
            model_name='channel',
            name='content',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel', to='channels.content'),
        ),
        migrations.AddField(
            model_name='channel',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channel',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='files',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='type_file',
            field=models.CharField(default='a', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='channel',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='channels.channel'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
